name: mounakassat_dz
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter  
  timeline_tile: ^2.0.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.0
  file_picker: ^10.2.1
  percent_indicator: ^4.2.5
  uuid: ^4.5.1
  http: ^1.4.0
  mime: ^2.0.0
  path: ^1.9.1
  http_parser: ^4.1.2
  sizer: ^3.0.0
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.2
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  flutter_dotenv: ^5.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_app_rebrand: ^1.0.3
  

flutter:  
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/kufi/NotoKufiArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/kufi/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/kufi/NotoKufiArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/kufi/NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/kufi/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/kufi/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/kufi/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/kufi/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kufi/NotoKufiArabic-Thin.ttf
          weight: 100
    - family: Generatorblack
      fonts:
        - asset: assets/fonts/Generator-Black.ttf

        